#!/bin/bash

VERSION=$(echo $VERSION | tr [:upper:] [:lower:])
TYPE=$(echo $TYPE | tr [:upper:] [:lower:])
mv /tmp/start* /$TYPE
cd /$TYPE

# Creates user and sets perms
umask 0002
chmod g+w /$(echo $TYPE | tr [:upper:] [:lower:])
chmod g+w /config

. ./start-utils

if [ $UID != 0 ]; then
    if [ $UID != $(id -u terraria) ]; then
        log "Changing uid of terraria to $UID"
        usermod -u $UID terraria
    fi
fi

if [ $GID != 0 ]; then
    if [ $UID != $(id -g terraria) ]; then
        log "Changing gid of terraria to $GID"
        groupmod -o -g $GID terraria
    fi
fi

if [ $(stat -c "%u" /config) != $UID ]; then
    log "Changing ownership of /config to $UID"
    chown -R terraria:terraria /config
fi

case $(echo $TYPE | tr [:upper:] [:lower:]) in
    tshock)
        exec ./start-deployTShock
        ;;
    modded)
        exec ./start-deployModded
        ;;
    vanilla | *)
        exec ./start-deployVanilla
        ;;
esac