#!/bin/bash

. ./start-utils
SERVER_CONFIG="/config/serverconfig.txt"

# Functions for setting the server properties
setServerProp () {
    local prop=$1
    local var=$2
    if [ -n "$var" ]; then
        if grep "${prop}" "$SERVER_CONFIG" > /dev/null ; then
            log "Setting ${prop} to '${var}'"
            sed -i "s/^${prop}=.*/${prop}=${var}/g" "$SERVER_CONFIG"
            sleep 0.5
        else
            log "Adding ${prop} with '${var}' in ${SERVER_CONFIG}"
            echo "${prop}=${var}" >> "$SERVER_CONFIG"
            sleep 0.5
        fi
    else
        log "Leaving ${prop} as" $(sed -n "s/^${prop}=/ /p" $SERVER_CONFIG)
        sleep 0.5
    fi
}

# Checks to see if custom conf is to be used
if [ -f /config/serverconfig.txt ]; then
    log "Serverconfig.txt found. Bypassing config creation"
else
    # Writes the default config
    mv /tmp/serverconfig.txt "$SERVER_CONFIG"; log "No user config found. Creating default config."
    if [ -z $WORLD ]; then
        W1="$(shuf -n1 /tmp/dictionaries/dict1.txt)"
        #echo $W1
        sleep 2
        WORLD=ChickenWing
    fi
    setServerProp "world" "/config/$WORLD.wld"
    setServerProp "autocreate" "$AUTOCREATE"
    setServerProp "seed" "$SEED"
    setServerProp "worldname" "$WORLDNAME"
    if [ ! -z $LANGUAGE ]; then
        case $(echo $LANGUAGE | tr [:upper:] [:lower:]) in
            en/us|en-us|en|us|1)
                if versionIsGreaterThan "1.3.4.4" ; then LANGUAGE=1; else
                LANGUAGE=en-US
                fi ;;
            de/DE|de-DE|de|2)
                if versionIsGreaterThan "1.3.4.4" ; then LANGUAGE=2; else
                LANGUAGE=de-DE
                fi ;;
            it/IT|it-IT|it|3)
                if versionIsGreaterThan "1.3.4.4" ; then LANGUAGE=3; else
                LANGUAGE=it-IT
                fi ;;
            fr/FR|fr-FR|fr|4)
                if versionIsGreaterThan "1.3.4.4" ; then LANGUAGE=4; else
                LANGUAGE=fr-FR
                fi ;;
            es/ES|es-ES|es|5)
                if versionIsGreaterThan "1.3.4.4" ; then LANGUAGE=5; else
                LANGUAGE=es-ES
                fi ;;
            ru/RU|ru-RU|ru)
                LANGUAGE=ru-RU ;;
            zh/Hans|zh-Hans|zh|hans)
                LANGUAGE=zh-Hans ;;
            pt/BR|pt-BR|pt|br)
                LANGUAGE=pt-BR ;;
            pl/PL|pl-PL|pl)
                LANGUAGE=pl-PL ;;
            *)
                debug "Unrecognized language! Using en/US"
                LANGUAGE=en-US;;
        esac
    fi
    setServerProp "language" "$LANGUAGE"
    if [ ! -z $DIFFICULTY ]; then
        case $(echo $DIFFICULTY | tr [:upper:] [:lower:]) in
            0|classic)
                DIFFICULTY=0 ;;
            1|expert)
                DIFFICULTY=1 ;;
            2|master)
                if versionIsGreaterThan "1.3.5.3" ; then
                    DIFFICULTY=2; else 
                    debug "Difficulty not found in $VERSION. Using expert instead."
                    DIFFICULTY=1
                fi ;;
            3|journey)
                if versionIsGreaterThan "1.3.5.3" ; then
                    DIFFICULTY=3; else
                    debug "Difficulty not found in $VERSION. Using classic instead."
                    DIFFICULTY=0
                fi ;;
            *)
                debug "$DIFFICULTY is out of bounds. Using classic instead."
                DIFFICULTY=0 ;;
        esac
    fi
    setServerProp "difficulty" "$DIFFICULTY"
    setServerProp "maxplayers" "$MAXPLAYERS"
    setServerProp "port" "$PORT"
    setServerProp "password" "$PASSWORD"
    setServerProp "motd" "$MOTD"
    setServerProp "worldpath" "$WORLDPATH"
    setServerProp "banlist" "$BANLIST"
    setServerProp "secure" "$SECURE"
    setServerProp "upnp" "$UPNP"
    setServerProp "npcstream" "$NPCSTREAM"
    setServerProp "priority" "$PRIORITY"
    # Journey Mode powers
    if versionIsGreaterThan "1.3.5.3"; then
        setServerProp "journeypermission_time_setfrozen" "$JOURNEYPERMISSION_TIME_SETFROZEN"
        setServerProp "journeypermission_time_setdawn" "$JOURNEYPERMISSION_TIME_SETDAWN"
        setServerProp "journeypermission_time_setnoon" "$JOURNEYPERMISSION_TIME_SETNOON"
        setServerProp "journeypermission_time_setdusk" "$JOURNEYPERMISSION_TIME_SETDUSK"
        setServerProp "journeypermission_time_setmidnight" "$JOURNEYPERMISSION_TIME_SETMIDNIGHT"
        setServerProp "journeypermission_godmode" "$JOURNEYPERMISSION_GODMODE"
        setServerProp "journeypermission_wind_setstrength" "$JOURNEYPERMISSION_WIND_SETSTRENGTH"
        setServerProp "journeypermission_rain_setstrength" "$JOURNEYPERMISSION_RAIN_SETSTRENGTH"
        setServerProp "journeypermission_time_setspeed" "$JOURNEYPERMISSION_TIME_SETSPEED"
        setServerProp "journeypermission_rain_setfrozen" "$JOURNEYPERMISSION_RAIN_SETFROZEN"
        setServerProp "journeypermission_wind_setfrozen" "$JOURNEYPERMISSION_WIND_SETFROZEN"
        setServerProp "journeypermission_increaseplacementrange" "$JOURNEYPERMISSION_INCREASEPLACEMENTRANGE"
        setServerProp "journeypermission_setdifficulty" "$JOURNEYPERMISSION_SETDIFFICULTY"
        setServerProp "journeypermission_biomespread_setfrozen" "$JOURNEYPERMISSION_BIOMESPREAD_SETFROZEN"
        setServerProp "journeypermission_setspawnrate" "$JOURNEYPERMISSION_SETSPAWNRATE"
    fi  
fi

#cat $SERVER_CONFIG
exec ./start-finalSetup