#!/bin/bash

. ./start-utils

# You've chosen vanilla! Time to get what version!
case $VERSION in
    1.3.3.3)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/server/terraria-server-1333.zip
        ;;
    1.3.4.4)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/server/terraria-server-1344.zip
        ;;
    1.3.5.3)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/server/terraria-server-1353.zip
        ;;
    1.4.0.1)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/server/terraria-server-1401.zip
        ;;
    1.4.0.2)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/system/dedicated_servers/archives/000/000/036/original/terraria-server-1402.zip
        ;;
    1.4.0.3)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/system/dedicated_servers/archives/000/000/037/original/terraria-server-1403.zip
        ;;
    1.4.0.4)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://www.terraria.org/system/dedicated_servers/archives/000/000/038/original/terraria-server-1404.zip
        ;;
    1.4.0.5)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://www.terraria.org/system/dedicated_servers/archives/000/000/039/original/terraria-server-1405.zip
        ;;
    1.4.1)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://www.terraria.org/system/dedicated_servers/archives/000/000/040/original/terraria-server-1410.zip
        ;;
    1.4.1.1)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://www.terraria.org/system/dedicated_servers/archives/000/000/041/original/terraria-server-1411.zip
        ;;
    1.4.1.2)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/system/dedicated_servers/archives/000/000/042/original/terraria-server-1412.zip
        ;;
    1.4.2)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/system/dedicated_servers/archives/000/000/043/original/terraria-server-142.zip
        ;;
    1.4.2.1)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/system/dedicated_servers/archives/000/000/044/original/terraria-server-1421.zip
        ;;
    1.4.2.2)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/system/dedicated_servers/archives/000/000/045/original/terraria-server-1422.zip
        ;;
    1.4.2.3 | latest)
        log "Downloading $TYPE Terraria running $VERSION"
        DOWNLOAD_URL=https://terraria.org/system/dedicated_servers/archives/000/000/046/original/terraria-server-1423.zip
        ;;
    *)
        VERSION=1.4.2.3
        log "Could not find a suitable version! Downloading $TYPE Terraria running $VERSION instead"
        DOWNLOAD_URL=https://terraria.org/system/dedicated_servers/archives/000/000/046/original/terraria-server-1423.zip
        ;;
esac

# Install time
mkdir /tmp/terraria
cd /tmp/terraria
curl -#L $DOWNLOAD_URL --output terraria-server.zip
unzip -q terraria-server.zip
mv */Linux/* /$TYPE
# Not technically needed but keeping it for backup
mv */Windows/serverconfig.txt /$TYPE/serverconfig-default.txt
chmod +x /$TYPE/TerrariaServer*
if [ ! -f /$TYPE/TerrariaServer ]; then 
    log "Missing TerrariaServer! Try a different version!"
    exit 1 
fi

# Server is ready to go, now we add the serverconfig.txt
cd /$TYPE
exec ./start-deployVanillaProps