#!/bin/bash

. ./start-utils

# Make the blank banlist
if [ ! -f /config/banlist.txt ]; then
    touch /config/banlist.txt
fi

rm -R /tmp/*

CMD="tmux new-session -s Terraria '/$TYPE/TerrariaServer -x64 -config /config/serverconfig.txt'"

log "Starting server! CMD: $CMD $@"
sleep 10
exec $CMD $@