#!/bin/bash

. ./start-utils

# Make the blank banlist
if [ ! -f /config/banlist.txt ]; then
    touch /config/banlist.txt
fi

rm -R /tmp/*

CMD=./$TYPE/TerrariaServer -x64 -config /config/serverconfig.txt

log "Starting server!"
exec $CMD $@